### ISSUE TITLE
Function suggestion panda.py

### ISSUE THREAD

**Issue by SAOJSM** [hldh214/recorder#20]
Hello sir,
I think this repo is one of best repo for recoding stream.
And I have a function suggest that add load session cookie function or add log in with own account to record the streaming login needed. Maybe you can add config.json to store these data and load when plugin match.
Hope to receive your reply.
Thank you for making contribution on github.

**Comment by hldh214** [comment]
I'm not sure if I understand correctly, but the 'session cookie' has already been implemented to pass through to the `get_stream` function. As for the 'login' part, since there **maybe** a captcha needed during login, there is no plan for it yet.
https://github.com/hldh214/recorder/blob/02756f0e8d7ab460354d1f03e632cad7138285a2/recorder/source/panda.py#L33-L38

**Comment by SAOJSM** [comment]
I know login function may need captcha, but can I know if any way add code that login with login session cookie.

**Comment by hldh214** [comment]
Allow me to clarify my previous comment. I demonstrated how to use a 'session cookie' to obtain a stream, and I wanted to make it clear that there are currently no plans to implement a username/password login function due to the potential need for a captcha. Thank you for your understanding.
